### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by eliasmalik** [FAC10/week-7-LMAO#58]
Several places will execute the callback twice in the error case. You need a `return` or an `else`:

https://github.com/FAC10/week-7-LMAO/blob/master/src/handler_home.js#L4
https://github.com/FAC10/week-7-LMAO/blob/master/src/postJoke.js#L5
https://github.com/FAC10/week-7-LMAO/blob/master/src/routes/post_submit.js#L8

If errors occur in handlers, be sure to always respond to the client with something, otherwise the request will hang and the user will get no feedback:

https://github.com/FAC10/week-7-LMAO/blob/master/src/routes/home.js#L9
https://github.com/FAC10/week-7-LMAO/blob/master/src/routes/post_submit.js#L8

**Comment by alexis-l8** [comment]
All points noted. Thanks Elias!
