### ISSUE TITLE
Heroku link on readme

### ISSUE THREAD

**Issue by RhodesPeter** [FAC10/week-7-LMAO#69]
Your link to the project on your README goes to `https` but the one at the top of your page goes to `http`.

I can't access the https one.

**Comment by RhodesPeter** [comment]
![screen shot 2017-04-07 at 10 45 14](https://cloud.githubusercontent.com/assets/18164707/24794919/61ec8a62-1b7f-11e7-9c32-e1c59fdb1427.png)

![screen shot 2017-04-07 at 10 45 22](https://cloud.githubusercontent.com/assets/18164707/24794920/61ef4a2c-1b7f-11e7-81df-1191169ce610.png)

**Comment by alexis-l8** [comment]
Relates to PR #77
